insert into services (id, name, category, price, starting_at, note, addon, sort_order) values
  ('manicure', 'Manicure', 'Nail Services', 15, false, null, false, 10),
  ('pedicure', 'Pedicure', 'Nail Services', 25, false, null, false, 20),
  ('mani-pedi', 'Manicure + Pedicure', 'Nail Services', 40, false, null, false, 30),
  ('full-set', 'Full Set', 'Nail Services', 40, true, null, false, 40),
  ('pink-white', 'Pink & White', 'Nail Services', 40, true, null, false, 50),
  ('dipping-powder', 'Dipping Powder', 'Nail Services', 40, true, null, false, 60),
  ('ombre-powder', 'Ombre Powder', 'Nail Services', 45, true, null, false, 70),
  ('press-on-manicure', 'Press-On Nails + Manicure', 'Nail Services', 20, true, null, false, 80),
  ('refill', 'Re-Fill', 'Nail Services', 35, true, null, false, 90),
  ('men-haircut', 'Men''s Haircut', 'Hair Services', 10, true, null, false, 100),
  ('women-haircut', 'Women''s Haircut', 'Hair Services', 15, true, null, false, 110),
  ('root-touch-up', 'Root Touch-Up', 'Hair Services', 35, true, null, false, 120),
  ('perm', 'Perm', 'Hair Services', 45, true, null, false, 130),
  ('highlight', 'Highlights', 'Hair Services', 45, true, null, false, 140),
  ('whole-package', 'Whole Package', 'Hair Services', 100, true, 'Highlight + color + haircut', false, 150),
  ('hair-treatment', 'Hair Treatment', 'Hair Services', 20, true, null, false, 160),
  ('ombre-color', 'Ombre Color', 'Hair Services', 150, false, null, false, 170),
  ('keratin-treatment', 'Keratin Treatment', 'Hair Services', 120, true, null, false, 180),
  ('straightening', 'Straightening', 'Hair Services', 220, true, null, false, 190),
  ('flat-iron', 'Flat Iron', 'Hair Services', 20, true, null, false, 200),
  ('additional-gel', 'Additional Gel', 'Nail Services', 8, false, null, true, 210),
  ('additional-ombre-gel', 'Additional Ombre Gel', 'Nail Services', 10, false, null, true, 220),
  ('marble-effect', 'Marble Effect', 'Nail Services', 10, false, null, true, 230),
  ('clear-gel', 'Clear Gel', 'Nail Services', 5, false, null, true, 240),
  ('additional-french', 'Additional French', 'Nail Services', 5, false, null, true, 250),
  ('callus-treatment', 'Callus Treatment', 'Nail Services', 5, false, null, true, 260),
  ('design', 'Design', 'Nail Services', 5, true, null, true, 270),
  ('gel-polish-change', 'Gel Polish Change', 'Nail Services', 15, false, null, true, 280),
  ('polish-change', 'Polish Change', 'Nail Services', 10, false, null, true, 290),
  ('eyebrow-threading', 'Eyebrow Threading', 'Facial Services', 10, false, null, false, 300),
  ('eyebrow-wax', 'Eyebrow Wax', 'Facial Services', 8, false, null, false, 310),
  ('lip-wax', 'Lip Wax', 'Facial Services', 5, false, null, false, 320),
  ('under-arm', 'Under-Arm', 'Facial Services', 14, false, null, false, 330),
  ('face-wax', 'Face Wax', 'Facial Services', 25, true, null, false, 340),
  ('leg-wax', 'Leg Wax', 'Facial Services', 25, true, null, false, 350),
  ('full-arm-wax', 'Full Arm Wax', 'Facial Services', 30, false, null, false, 360),
  ('bikini-wax', 'Bikini Wax', 'Facial Services', 30, true, null, false, 370),
  ('brazilian-wax', 'Brazilian Wax', 'Facial Services', 40, true, null, false, 380),
  ('eyelash-extensions', 'Eyelash Extensions', 'Facial Services', 35, true, null, false, 390),
  ('eyelash-removal', 'Eyelash Removal', 'Facial Services', 10, false, null, false, 400),
  ('facial-40', 'Facial (40 mins)', 'Facial Services', 40, true, null, false, 410);

insert into staff (id, name, role, categories, sort_order) values
  ('tina', 'Tina', 'Nail Tech', array['Nail Services','Facial Services']::service_category[], 10),
  ('finn', 'Finn', 'Hair Stylist & Nail Tech', array['Hair Services','Nail Services']::service_category[], 20),
  ('tim', 'Tim', 'Nail Tech', array['Nail Services']::service_category[], 30),
  ('sheila', 'Sheila', 'Hair Stylist & Nail Tech', array['Hair Services','Nail Services']::service_category[], 40),
  ('liz', 'Liz', 'Nail Tech', array['Nail Services']::service_category[], 50),
  ('christine', 'Christine', 'Hair Stylist & Nail Tech', array['Hair Services','Nail Services','Facial Services']::service_category[], 60),
  ('mary', 'Mary', 'Hair Stylist & Nail Tech', array['Hair Services','Nail Services']::service_category[], 70);

insert into staff_specialties (staff_id, label, service_id, category, sort_order) values
  ('tina', 'Nail Services', null, 'Nail Services', 10),
  ('tina', 'Facials', null, 'Facial Services', 20),
  ('finn', 'Men''s Haircuts', 'men-haircut', null, 10),
  ('finn', 'Color', null, 'Hair Services', 20),
  ('finn', 'Manicure', 'manicure', null, 30),
  ('finn', 'Pedicure', 'pedicure', null, 40),
  ('tim', 'Manicure', 'manicure', null, 10),
  ('tim', 'Pedicure', 'pedicure', null, 20),
  ('sheila', 'Hair Services', null, 'Hair Services', 10),
  ('sheila', 'Nail Services', null, 'Nail Services', 20),
  ('liz', 'Nail Services', null, 'Nail Services', 10),
  ('christine', 'Haircuts', null, 'Hair Services', 10),
  ('christine', 'Nail Services', null, 'Nail Services', 20),
  ('christine', 'Facials', null, 'Facial Services', 30),
  ('mary', 'Hair Services', null, 'Hair Services', 10),
  ('mary', 'Manicure', 'manicure', null, 20),
  ('mary', 'Pedicure', 'pedicure', null, 30);
